project:
  type: website 
  output-dir: docs
  
website:
  title: "Yiwen Zhang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

